# Generated by Django 3.1 on 2020-08-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20200830_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='sobrenome',
        ),
    ]
