# Generated by Django 3.1 on 2020-08-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20200830_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='salary',
        ),
        migrations.AddField(
            model_name='person',
            name='idade',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
    ]
