# Generated by Django 3.1 on 2020-08-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_person_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default=-1.0, max_length=30),
            preserve_default=False,
        ),
    ]
