# Generated by Django 3.1 on 2020-08-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='data_nascimento',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
    ]
